# Tidene Códigos - Classificadores

### Recebe os dados

In [5]:
import numpy as np
import pandas as pd
import nltk
import sklearn
import gensim
import pickle

C:\Users\bruno\AppData\Local\Continuum\anaconda3\envs\curso\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [6]:
# copiei aqui as classes definidas quando foram criados os vetorizadores... ela poderia ser importada do notebook no qual foi definida
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import *    #https://www.nltk.org/api/nltk.tokenize.html

class LemmaTokenizer(object):
    def __init__(self):
        self.wnl = WordNetLemmatizer()
        self.tokenizer = nltk.tokenize.RegexpTokenizer("[a-zA-Z']+")
    def __call__(self, doc):
        return [self.wnl.lemmatize(t) for t in self.tokenizer.tokenize(doc) if (len(t)>2)]

class StemTokenizer(object):
    def __init__(self):
        self.stemmer = PorterStemmer()
        self.tokenizer = nltk.tokenize.RegexpTokenizer("[a-zA-Z']+")
    def __call__(self, doc):
        return [self.stemmer.stem(t) for t in self.tokenizer.tokenize(doc) if (len(t)>2)]


In [7]:
# carrega a matriz de features e o vetorizador e a matriz de features 
tfidf_vectorizer = pickle.load(open("tfidf_vectorizer.pickle", "rb"))
X_train_tfidf = pickle.load(open("X_train_tfidf.pickle", "rb"))

X_train_tfidf.shape   # matriz de features

(5250, 38515)

#### Lê os textos e as classes de treinamento - e também as classes do arquivo de treinamento

In [8]:
# AQUI PODE-SE MUDAR QUAL A CLASSE QUE VAI SER CONSIDERADA
from sklearn.model_selection import train_test_split
import pandas as pd
corpus =  pd.read_csv('data/train_min.csv',encoding='utf8')

corpus_train , corpus_test =  train_test_split(corpus, train_size=0.7)

train_classes = corpus_train['sentiment'].values.tolist()

test_docs = corpus_test['review'].values.tolist()
test_classes = corpus_test['sentiment'].values.tolist()


X_test_tfidf = tfidf_vectorizer.transform(test_docs) #representa os documentos com o padrao treinado


C:\Users\bruno\AppData\Local\Continuum\anaconda3\envs\curso\lib\site-packages\sklearn\model_selection\_split.py:2069: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)
C:\Users\bruno\AppData\Local\Continuum\anaconda3\envs\curso\lib\site-packages\sklearn\feature_extraction\text.py:286: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['ha', 'le', 'wa'] not in stop_words.
  sorted(inconsistent))


In [9]:
X_test_tfidf.shape

(2250, 38515)

### Classificador Bayesiano

In [11]:
#http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html
from sklearn.naive_bayes import MultinomialNB
clf_NB = MultinomialNB().fit(X_train_tfidf, train_classes)

##### Predizendo classes para o texto novo

In [25]:
predicted_NB = clf_NB.predict(X_test_tfidf)
print("Acurácia: ", np.mean(predicted_NB == test_classes))           

print('classe real => classe predita')

for real, pred in zip(test_classes, predicted_NB):
    print((real,pred))


Acurácia:  0.5115555555555555
classe real => classe predita
(1, 1)
(0, 0)
(1, 1)
(0, 1)
(0, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 0)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(0, 1)
(0, 1)
(0, 1)
(0, 0)
(0, 1)
(0, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 1)
(0, 0)
(1, 0)
(1, 1)
(0, 1)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 0)
(1, 0)
(0, 1)
(0, 0)
(0, 1)
(0, 0)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(0, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(0, 1)
(0, 1)
(0, 0)
(1, 0)
(0, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 0)
(0, 1)
(1, 1)
(1, 0)
(0, 0)
(0

(1, 0)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 0)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 0)
(1, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(0, 1)
(0, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(0, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(0, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 1)
(0, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 1)
(0, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 1)
(1, 0)
(0, 0)
(1, 0)
(0, 1)
(0, 0)
(1, 1)
(1, 1)
(0, 1)
(1, 0)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(0, 0)
(1, 1)
(0, 1)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(0, 1)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(0, 1)
(0, 1)
(0, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 1)
(1, 1)
(0, 1)
(0, 1)

#### Avaliação

In [37]:
from sklearn import metrics
print(metrics.classification_report(test_classes, predicted_NB,target_names=["negative","positive"]))


              precision    recall  f1-score   support

    negative       0.50      0.50      0.50      1106
    positive       0.52      0.52      0.52      1144

   micro avg       0.51      0.51      0.51      2250
   macro avg       0.51      0.51      0.51      2250
weighted avg       0.51      0.51      0.51      2250



In [38]:
# Matriz de Confusao
print(metrics.confusion_matrix(test_classes, predicted_NB))

[[552 554]
 [545 599]]


### Classificadore SGDC

In [39]:
#http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html
from sklearn.linear_model import SGDClassifier

clf_SGDC = SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42,max_iter=5, tol=None)
clf_SGDC.fit(X_train_tfidf, train_classes)
predicted_SGDC = clf_SGDC.predict(X_test_tfidf)

print("Acurácia: ", np.mean(predicted_SGDC == test_classes))           

print('classe real => classe predita')

for real, pred in zip(test_classes, predicted_SGDC):
    print((real,pred))


Acurácia:  0.5231111111111111
classe real => classe predita
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(0, 1)
(0, 0)
(1, 0)
(0, 1)
(0, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 0)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(0, 1)
(0, 1)
(0, 0)
(0, 0)
(0, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 1)
(0, 0)
(1, 0)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 0)
(1, 0)
(0, 1)
(0, 1)
(0, 1)
(0, 0)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(0, 1)
(1, 0)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 1)
(0, 1)
(0, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 1)
(0, 0)
(0, 1)
(1, 0)
(0, 0)
(1, 0)
(0, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(0

(0, 1)
(0, 1)
(0, 1)
(0, 1)
(0, 0)
(1, 1)
(1, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(0, 1)
(0, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 1)
(0, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 1)
(0, 1)
(1, 1)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 0)
(0, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(0, 1)
(1, 1)
(1, 1)
(0, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 1)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 1)
(1, 1)
(0, 0)
(1, 0)
(0, 0)
(0, 1)
(1, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 0)
(0, 1)
(1, 1)
(0, 1)
(1, 0)
(0, 0)
(1, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 1)
(0, 1)
(1, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(0, 1)
(0, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 0)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(0, 1)
(0, 0)

#### Métricas de avaliação

In [36]:
from sklearn import metrics
print(metrics.classification_report(test_classes, predicted_SGDC,target_names=["negative","positive"]))
      

              precision    recall  f1-score   support

    positive       0.52      0.40      0.45      1106
    negative       0.53      0.64      0.58      1144

   micro avg       0.52      0.52      0.52      2250
   macro avg       0.52      0.52      0.52      2250
weighted avg       0.52      0.52      0.52      2250



In [29]:
print("Matriz de confusão")
print(metrics.confusion_matrix(test_classes, predicted_SGDC))

Matriz de confusão
[[446 660]
 [413 731]]


### Classificador SVM

In [30]:
#http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html
from sklearn.svm import LinearSVC

clf_SVC = LinearSVC(random_state=0)
clf_SVC.fit(X_train_tfidf, train_classes)
predicted_SVC = clf_SVC.predict(X_test_tfidf)

print("Acurácia: ", np.mean(predicted_SVC == test_classes))           


print('classe real => classe predita')

for real, pred in zip(test_classes, predicted_SVC):
    print((real,pred))



Acurácia:  0.5088888888888888
classe real => classe predita
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 0)
(1, 1)
(0, 0)
(1, 0)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(0, 0)
(0, 1)
(0, 1)
(0, 0)
(0, 1)
(0, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 1)
(0, 0)
(1, 0)
(1, 0)
(0, 1)
(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 0)
(1, 0)
(0, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 0)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 0)
(0, 0)
(0, 1)
(0, 1)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(0, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 1)
(0, 0)
(1, 0)
(0, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(0

(1, 1)
(1, 0)
(1, 1)
(1, 0)
(1, 0)
(1, 0)
(1, 1)
(1, 0)
(0, 1)
(0, 0)
(1, 0)
(0, 0)
(1, 0)
(1, 1)
(1, 0)
(1, 1)
(1, 1)
(1, 1)
(0, 1)
(1, 1)
(0, 1)
(0, 1)
(0, 1)
(1, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 1)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 0)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(1, 1)
(0, 0)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(0, 0)
(1, 1)
(0, 0)
(1, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 1)
(0, 0)
(1, 0)
(0, 1)
(0, 1)
(1, 0)
(0, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(0, 1)
(0, 1)
(1, 1)
(0, 1)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 0)
(1, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 1)
(1, 1)
(1, 1)
(1, 0)
(0, 1)
(1, 0)
(1, 1)
(0, 1)
(0, 0)
(0, 0)
(1, 1)
(0, 0)
(0, 0)
(1, 1)
(1, 1)
(0, 1)
(1, 0)
(0, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 0)
(0, 0)
(0, 0)
(1, 1)
(0, 1)
(1, 0)
(0, 1)
(1, 0)
(0, 0)
(0, 1)
(1, 1)
(0, 0)
(0, 1)
(1, 1)
(1, 1)
(1, 0)
(0, 1)
(0, 1)
(0, 0)
(1, 1)
(1, 0)
(1, 1)

#### Avaliação

In [35]:
from sklearn import metrics
print(metrics.classification_report(test_classes, predicted_SVC))

              precision    recall  f1-score   support

           0       0.50      0.53      0.52      1106
           1       0.52      0.49      0.50      1144

   micro avg       0.51      0.51      0.51      2250
   macro avg       0.51      0.51      0.51      2250
weighted avg       0.51      0.51      0.51      2250



#### Matriz de Confusão

In [32]:
print("Matriz de confusão")
print(metrics.confusion_matrix(test_classes, predicted_SVC))

Matriz de confusão
[[587 519]
 [586 558]]
